Fix missing libz linking for Stratis-qt build
Produced build error when compiling with openssl1.0.2l (openssl compiled with zlib)

```bash
/usr/bin/ld: /home/ader/coins/DEPS/openssl1.0.2l/lib/libcrypto.a(c_zlib.o): undefined reference to symbol 'deflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:592: recipe for target 'stratis-qt' failed
make: *** [stratis-qt] Error 1
```
Simple fix to add library link `-lz` to stratis-qt.pro